name: fumode_client_mobile
description: "A Flutter client for Fumode applications."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fumode_ui:
    git:
      url: git@github.com:Tr-n-Huy-Flutter/fumode_ui.git
      ref: develop

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
     - family: PlusJakartaSans
       fonts:
         - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
           weight: 200
           style: italic
         - asset: assets/fonts/PlusJakartaSans-Light.ttf
           weight: 300
         - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
           weight: 300
           style: italic
         - asset: assets/fonts/PlusJakartaSans-Regular.ttf
           weight: 400
         - asset: assets/fonts/PlusJakartaSans-Italic.ttf
           weight: 400
           style: italic
         - asset: assets/fonts/PlusJakartaSans-Medium.ttf
           weight: 500
         - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: assets/fonts/PlusJakartaSans-Bold.ttf
           weight: 700
         - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
           weight: 800
           style: italic




